# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/better_simon',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/better_simon',
                'lib_path': 'better_simon'},
  'syms': {'better_simon.core': {'better_simon.core.foo': ('core.html#foo', 'better_simon/core.py')}}}
